---

- name: "Install required packages to configure repositories"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-software-properties
    - python3-software-properties
  when: ansible_lsb.id == 'Ubuntu'

- name: "Configure Openstack {{ openio_openstack_release }} release repository"
  apt_repository:
    repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu {{ ansible_lsb.codename }}-updates/pike main"
    state: present
    filename: 'cloudarchive-pike'
  when: ansible_lsb.id == 'Ubuntu'

- name: "Setup repository key for Openstack repository"
  apt_key:
    id: 5EDB1B62EC4926EA
    keyserver: keyserver.ubuntu.com

- name: "Update APT cache"
  apt:
    update_cache: yes

...
